/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xml_library_services_RestartSevice */

#ifndef _Included_com_xml_library_services_RestartSevice
#define _Included_com_xml_library_services_RestartSevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xml_library_services_RestartSevice
 * Method:    restartAservice
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_xml_library_services_RestartSevice_restartAservice
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
